/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    cms_users: CmsUserAuthOperations;
  };
  blocks: {};
  collections: {
    cms_users: CmsUser;
    cms_media: CmsMedia;
    cms_products: CmsProduct;
    cms_product_categories: CmsProductCategory;
    cms_product_category_groups: CmsProductCategoryGroup;
    cms_product_category_lists: CmsProductCategoryList;
    content_pages: ContentPage;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    cms_users: CmsUsersSelect<false> | CmsUsersSelect<true>;
    cms_media: CmsMediaSelect<false> | CmsMediaSelect<true>;
    cms_products: CmsProductsSelect<false> | CmsProductsSelect<true>;
    cms_product_categories: CmsProductCategoriesSelect<false> | CmsProductCategoriesSelect<true>;
    cms_product_category_groups: CmsProductCategoryGroupsSelect<false> | CmsProductCategoryGroupsSelect<true>;
    cms_product_category_lists: CmsProductCategoryListsSelect<false> | CmsProductCategoryListsSelect<true>;
    content_pages: ContentPagesSelect<false> | ContentPagesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'no' | 'se' | 'dk' | 'de' | 'fi' | 'it' | 'pl' | 'uk';
  user: CmsUser & {
    collection: 'cms_users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface CmsUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms_users".
 */
export interface CmsUser {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms_media".
 */
export interface CmsMedia {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms_products".
 */
export interface CmsProduct {
  id: number;
  product_id?: number | null;
  sku: string;
  sku2?: string | null;
  category?: (number | null) | CmsProductCategory;
  description_en?: string | null;
  description_no?: string | null;
  description_se?: string | null;
  description_dk?: string | null;
  description_de?: string | null;
  description_fi?: string | null;
  description_it?: string | null;
  description_pl?: string | null;
  description_uk?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms_product_categories".
 */
export interface CmsProductCategory {
  id: number;
  category: string;
  en?: string | null;
  no?: string | null;
  se?: string | null;
  dk?: string | null;
  de?: string | null;
  fi?: string | null;
  it?: string | null;
  pl?: string | null;
  uk?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms_product_category_groups".
 */
export interface CmsProductCategoryGroup {
  id: number;
  name: string;
  full_path: string;
  parent_group?: (number | null) | CmsProductCategoryGroup;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms_product_category_lists".
 */
export interface CmsProductCategoryList {
  id: number;
  name: string;
  full_path: string;
  parent_product_group: number | CmsProductCategoryGroup;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content_pages".
 */
export interface ContentPage {
  id: number;
  slug: string;
  localizedSlug?: string | null;
  blocks?: HeroBlock[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  color?: ('dark' | 'light' | 'white') | null;
  imagePlacement?: ('left' | 'right' | 'behind') | null;
  squareImage?: boolean | null;
  fullWidth?: boolean | null;
  imageFade?: boolean | null;
  image: number | CmsMedia;
  title?: string | null;
  text?: string | null;
  link?: {
    title?: string | null;
    target?: string | null;
  };
  textLink?: {
    title?: string | null;
    target?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'cms_users';
        value: number | CmsUser;
      } | null)
    | ({
        relationTo: 'cms_media';
        value: number | CmsMedia;
      } | null)
    | ({
        relationTo: 'cms_products';
        value: number | CmsProduct;
      } | null)
    | ({
        relationTo: 'cms_product_categories';
        value: number | CmsProductCategory;
      } | null)
    | ({
        relationTo: 'cms_product_category_groups';
        value: number | CmsProductCategoryGroup;
      } | null)
    | ({
        relationTo: 'cms_product_category_lists';
        value: number | CmsProductCategoryList;
      } | null)
    | ({
        relationTo: 'content_pages';
        value: number | ContentPage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'cms_users';
    value: number | CmsUser;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'cms_users';
    value: number | CmsUser;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms_users_select".
 */
export interface CmsUsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms_media_select".
 */
export interface CmsMediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms_products_select".
 */
export interface CmsProductsSelect<T extends boolean = true> {
  product_id?: T;
  sku?: T;
  sku2?: T;
  category?: T;
  description_en?: T;
  description_no?: T;
  description_se?: T;
  description_dk?: T;
  description_de?: T;
  description_fi?: T;
  description_it?: T;
  description_pl?: T;
  description_uk?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms_product_categories_select".
 */
export interface CmsProductCategoriesSelect<T extends boolean = true> {
  category?: T;
  en?: T;
  no?: T;
  se?: T;
  dk?: T;
  de?: T;
  fi?: T;
  it?: T;
  pl?: T;
  uk?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms_product_category_groups_select".
 */
export interface CmsProductCategoryGroupsSelect<T extends boolean = true> {
  name?: T;
  full_path?: T;
  parent_group?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms_product_category_lists_select".
 */
export interface CmsProductCategoryListsSelect<T extends boolean = true> {
  name?: T;
  full_path?: T;
  parent_product_group?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content_pages_select".
 */
export interface ContentPagesSelect<T extends boolean = true> {
  slug?: T;
  localizedSlug?: T;
  blocks?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  color?: T;
  imagePlacement?: T;
  squareImage?: T;
  fullWidth?: T;
  imageFade?: T;
  image?: T;
  title?: T;
  text?: T;
  link?:
    | T
    | {
        title?: T;
        target?: T;
      };
  textLink?:
    | T
    | {
        title?: T;
        target?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}